# general config
spring:
  application:
    name: oj-backend
  # default dev environment
  profiles:
    active: dev
  # swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session config
  session:
    # todo uncomment to open distribute session（first config Redis）
#     store-type: redis
    # 30 day expire
     timeout: 2592000
  # database config
  # todo database config suit to environment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.cdbdfu3gs98i.us-east-1.rds.amazonaws.com:3306/online_judge
    username: admin
    password: xzh111xzh111
# my local environment
#    url: jdbc:mysql://localhost:3306/online_judge
#    username: root
#    password: xzh111
  # Redis config
  # todo replace redis config suit to environment
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # Elasticsearch config
  # todo replace Elasticsearch config suit to environment
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
server:
  address: 0.0.0.0
  port: 8000
  servlet:
    context-path: /api
    # cookie 30 days expire
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # entity name for delete logic
      logic-delete-value: 1 # delete logic value（default 1）
      logic-not-delete-value: 0 # not delete logic value（default 0）
codesandbox:
  type: Remote
  IP: 52.91.174.68
  port: 8081